### ISSUE TITLE
Genji shell panics

### ISSUE THREAD

**Issue by YassineE** [asdine/genji#67]
When trying to run a basic sql count query I have a panic:
```
genji> select count(panic: interface conversion: error is *errors.errorString, not *parser.ParseError

goroutine 1 [running]:
github.com/asdine/genji/cmd/genji/shell.completer(0xc00009c390, 0xe, 0xe, 0x400, 0x0, 0x0)
	/Users/Yasss/dev/go/pkg/mod/github.com/asdine/genji/cmd/genji@v0.5.0/shell/shell.go:297 +0x4a0
github.com/c-bata/go-prompt.(*CompletionManager).Update(...)
	/Users/Yasss/dev/go/pkg/mod/github.com/c-bata/go-prompt@v0.2.3/completion.go:69
github.com/c-bata/go-prompt.(*Prompt).Run(0xc00017c400)
	/Users/Yasss/dev/go/pkg/mod/github.com/c-bata/go-prompt@v0.2.3/prompt.go:95 +0x6af
github.com/asdine/genji/cmd/genji/shell.Run(0xc000129920, 0xc000129920, 0xc000132840)
	/Users/Yasss/dev/go/pkg/mod/github.com/asdine/genji/cmd/genji@v0.5.0/shell/shell.go:113 +0x2aa
main.main.func1(0xc0001449a0, 0x0, 0x0)
	/Users/Yasss/dev/go/pkg/mod/github.com/asdine/genji/cmd/genji@v0.5.0/main.go:53 +0x163
github.com/urfave/cli.HandleAction(0x45e5f20, 0x46c2a60, 0xc0001449a0, 0x0, 0x0)
	/Users/Yasss/dev/go/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:523 +0x11a
github.com/urfave/cli.(*App).Run(0xc0001d8000, 0xc000128020, 0x2, 0x2, 0x0, 0x0)
	/Users/Yasss/dev/go/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:285 +0x630
main.main()
	/Users/Yasss/dev/go/pkg/mod/github.com/asdine/genji/cmd/genji@v0.5.0/main.go:59 +0x25e
```

**Comment by YassineE** [comment]
Closing this one, it has been fixed in #70.
